---
title: "STATS506_problemset1_Takehisa_r2"
format: pdf
editor: visual
---

#a.Import the data into a data.frame in R. Use the information in the “abalone.names” file to give appropriate column names. (Note: Downloading and unzipping the file can take place outside of your submitted document, but importing the file should be in the submission.)

#function to import #inputs:data set abalones

abalone_data \<- read.csv( "abalone.data", header = FALSE )

#function to make column

#inputs: name of each columm

# outputs: culumn-name

colnames(abalone_data) <- c( "Sex", "Length", "Diameter", "Height", "Whole_weight", "Shucked_weight", "Viscera_weight", "Shell_weight", "Rings" )

# b.The data contains information on three different sexes of abalone. Report the number of observations belonging to each sex.

# Answer Male:1528, Female:1307, Infant:1342

#function to show the number of observations of each sex
#inputs:sex of each abalone
#outputs:the number of the number of observations of each sex
table(abalone_data\$Sex)

# c.1.Which weight has the highest correlation with rings?
# Answer:Shell weight 

#function to compute correlation between each weight and Rings
#inputs:each weight and ring size of abalone 
#outputs:correlation between each and Rings
cor(abalone_data$Whole_weight,abalone_data$Rings)
cor(abalone_data$Shucked_weight,abalone_data$Rings)
cor(abalone_data$Viscera_weight,abalone_data$Rings)
cor(abalone_data$Shell_weight,abalone_data$Rings)

# c.2. For that weight, which sex has the highest correlation?

install.packages("dplyr")

sex_correlations <- abalon_data %>%
  group_by(sex) %>%


